url: "https://cr1ttr.github.io"
title: "cr1ttr" 


github: "https://github.com/cr1ttr"
discord: "https://discord.com/users/488889057603092480"
bluesky: "https://bsky.app/profile/cr1ttr.bsky.social"
queer_coded: 
  discord: "https://discord.gg/hghUekrPqR"
  webring: "https://webring.queercoded.dev/"